name: Caches_Build_And_Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install CMake
      run: |
        sudo apt-get update -y
        sudo apt-get install cmake -y
        cmake --version
      
    - name: Build and test
      run: |
        cmake .
        make
        ./Caches
